program MemoryCells;

{$R *.res}

{$R *.dres}

uses
  System.StartUpCopy,
  FMX.Forms,
  MemoryCellsUnit in 'MemoryCellsUnit.pas' {MainForm},
  ToolsUnit in '..\..\DevelopmentsCollection\ToolsUnit.pas',
  BaseThreadUnit in 'Threads\BaseThreadUnit.pas',
  DeleteFolderThreadUnit in 'Threads\DeleteFolderThreadUnit.pas',
  InsertCellThreadUnit in 'Threads\InsertCellThreadUnit.pas',
  InsertFolderThreadUnit in 'Threads\InsertFolderThreadUnit.pas',
  LoadCellThreadUnit in 'Threads\LoadCellThreadUnit.pas',
  UpdateCellThreadUnit in 'Threads\UpdateCellThreadUnit.pas',
  UpdateFolderThreadUnit in 'Threads\UpdateFolderThreadUnit.pas',
  BorderFrameUnit in '..\..\DevelopmentsCollection\BorderFrame\BorderFrameUnit.pas' {BorderFrame: TFrame},
  BaseCellFrameUnit in 'Frames\BaseCellFrameUnit.pas' {BaseCellFrame: TFrame},
  CurrentFolderFrameUnit in 'Frames\CurrentFolderFrameUnit.pas' {CurrentFolderFrame: TFrame},
  EditFolderNameFrameUnit in 'Frames\EditFolderNameFrameUnit.pas' {EditFolderNameFrame: TFrame},
  CellUnitFrameUnit in 'Frames\CellUnitFrameUnit.pas' {CellUnitFrame: TFrame},
  FolderUnitFrameUnit in 'Frames\FolderUnitFrameUnit.pas' {FolderUnitFrame: TFrame},
  CellMemoFrameUnit in 'Frames\CellMemoFrameUnit.pas' {CellMemoFrame: TFrame},
  DeleteCellThreadUnit in 'Threads\DeleteCellThreadUnit.pas',
  SearchThreadUnit in 'Threads\SearchThreadUnit.pas',
  LoadCatalogThreadUnit in 'Threads\LoadCatalogThreadUnit.pas',
  LoadCellsByIdListThreadUnit in 'Threads\LoadCellsByIdListThreadUnit.pas',
  SearchTextFrameUnit in 'Frames\SearchTextFrameUnit.pas' {SearchTextFrame: TFrame},
  BackupThreadUnit in 'Threads\BackupThreadUnit.pas',
  BackupStarterThreadUnit in 'BackupStarterThreadUnit.pas',
  UpdateCellAttributesThreadUnit in 'Threads\UpdateCellAttributesThreadUnit.pas',
  DestinationFolderNavigatorFrameUnit in 'Frames\DestinationFolderNavigatorFrameUnit.pas' {DestinationFolderNavigatorFrame: TFrame},
  LoadDestinationCatalogThreadUnit in 'Threads\LoadDestinationCatalogThreadUnit.pas',
  MoveCellsThreadUnit in 'Threads\MoveCellsThreadUnit.pas',
  KeyCatcherThreadUnit in 'Threads\KeyCatcherThreadUnit.pas',
  KeyHandlerUnit in 'KeyHandlerUnit.pas',
  MemoryFileUnit in '..\..\DevelopmentsCollection\MemoryFileUnit.pas',
  TransportContainerUnit in '..\..\DevelopmentsCollection\UTCS\TransportContainerUnit.pas',
  UTCSTypesUnit in '..\..\DevelopmentsCollection\UTCS\UTCSTypesUnit.pas',
  UTClientManagerUnit in 'UTClientManagerUnit.pas',
  LockedListExtUnit in '..\..\DevelopmentsCollection\LockedListExtUnit.pas',
  UTClientUnit in '..\..\DevelopmentsCollection\UTCS\UTClientUnit.pas',
  UTClientRequestUnit in '..\MemoryCellsCommon\UTClientRequestUnit.pas',
  PingTimeoutThreadUnit in '..\..\DevelopmentsCollection\UTCS\PingTimeoutThreadUnit.pas',
  DBAccessUnit in '..\MemoryCellsCommon\DBAccessUnit.pas',
  CellUnit in '..\MemoryCellsCommon\CellUnit.pas',
  ExceptionContainerUnit in '..\MemoryCellsCommon\ExceptionContainerUnit.pas',
  ServerRepliesParserUnit in 'ServerRepliesParserUnit.pas',
  UTServerReplyUnit in '..\MemoryCellsCommon\UTServerReplyUnit.pas',
  FMX.MemoTextHighlighterUnit in '..\..\DevelopmentsCollection\FMX.MemoTextHighlighterUnit.pas',
  FMX.ShowNoteFormUnit in '..\..\DevelopmentsCollection\FMX.ShowNoteFormUnit\FMX.ShowNoteFormUnit.pas' {NoteForm},
  FMX.TrayIcon.Win in '..\..\DevelopmentsCollection\FMX.TrayIcon.Win.pas',
  CustomThreadUnit in '..\..\DevelopmentsCollection\CustomThreadUnit.pas',
  CellReminderDateTimeFrameUnit in 'Frames\CellReminderDateTimeFrameUnit.pas' {CellReminderDateTimeFrame: TFrame},
  FMX.DateTimeControlsTuningUnit in '..\..\DevelopmentsCollection\FMX.DateTimeControlsTuningUnit.pas',
  LoadCellReminderThreadUnit in 'Threads\LoadCellReminderThreadUnit.pas',
  CellReminderThreadUnit in 'Threads\CellReminderThreadUnit.pas',
  FMX.OnClickReplacerUnit in '..\..\DevelopmentsCollection\FMX.OnClickReplacerUnit.pas',
  CellReminderFormUnit in 'Forms\CellReminderFormUnit.pas' {CellReminderForm},
  UpdateCellReminderThreadUnit in 'Threads\UpdateCellReminderThreadUnit.pas',
  CommonUnit in 'CommonUnit.pas',
  BaseSettingUnit in 'Frames\Settings\BaseSettingUnit.pas' {BaseSettingFrame: TFrame},
  BackupSettingFrameUnit in 'Frames\Settings\BackupSettingFrameUnit.pas' {BackupSettingFrame: TFrame},
  LaunchSettingFrameUnit in 'Frames\Settings\LaunchSettingFrameUnit.pas' {LaunchSettingFrame: TFrame},
  SettingsFrameUnit in 'Frames\Settings\SettingsFrameUnit.pas' {SettingsFrame: TFrame},
  FileToolsUnit in '..\..\DevelopmentsCollection\FileToolsUnit.pas',
  FMX.ImageToolsUnit in '..\..\DevelopmentsCollection\FMX.ImageToolsUnit.pas',
  FMX.Theme in '..\..\DevelopmentsCollection\FMX.Theme\FMX.Theme.pas',
  FMX.Theme.Types in '..\..\DevelopmentsCollection\FMX.Theme\FMX.Theme.Types.pas',
  MCParamsUnit in '..\MemoryCellsCommon\MCParamsUnit.pas',
  ParamsExtUnit in '..\..\DevelopmentsCollection\ParamsExt\ParamsExtUnit.pas',
  FMX.ControlToolsUnit in '..\..\DevelopmentsCollection\FMX.ControlToolsUnit.pas',
  DateTimeToolsUnit in '..\..\DevelopmentsCollection\DateTimeToolsUnit.pas',
  DBToolsUnit in '..\..\DevelopmentsCollection\SQLite\DBToolsUnit.pas',
  LoadRemindCellsThreadUnit in 'Threads\LoadRemindCellsThreadUnit.pas',
  TextExtractorUnit in '..\..\DevelopmentsCollection\FilePacker\TextExtractorUnit.pas',
  FilePackerUnit in '..\..\DevelopmentsCollection\FilePacker\FilePackerUnit.pas',
  SQLTemplatesUnit in '..\..\DevelopmentsCollection\SQL\SQLTemplatesUnit.pas',
  ThreadFactoryRegistryUnit in '..\..\DevelopmentsCollection\ThreadFactoryRegistryUnit.pas',
  ThreadRegistryUnit in '..\..\DevelopmentsCollection\ThreadRegistryUnit.pas',
  ObjectRegistryUnit in '..\..\DevelopmentsCollection\ObjectRegistryUnit.pas',
  FMX.FormExtUnit in '..\..\DevelopmentsCollection\FMX.FormExtUnit.pas',
  ThreadFactoryUnit in '..\..\DevelopmentsCollection\ThreadFactoryUnit.pas',
  FMX.ShowStatusUnit in 'Threads\FMX.ShowStatusUnit.pas',
  FMX.PopupMenuExt.BaseClass in '..\..\DevelopmentsCollection\FMX.PopupMenuExt\FMX.PopupMenuExt.BaseClass.pas',
  FMX.PopupMenuExt in '..\..\DevelopmentsCollection\FMX.PopupMenuExt\FMX.PopupMenuExt.pas',
  FMX.PopupMenuExt.Windows in '..\..\DevelopmentsCollection\FMX.PopupMenuExt\FMX.PopupMenuExt.Windows.pas',
  FMX.PopupMenuExt.Form in '..\..\DevelopmentsCollection\FMX.PopupMenuExt\FMX.PopupMenuExt.Form.pas',
  FMX.PopupMenuExt.Layout in '..\..\DevelopmentsCollection\FMX.PopupMenuExt\FMX.PopupMenuExt.Layout.pas',
  FMX.PopupMenuExt.Constants in '..\..\DevelopmentsCollection\FMX.PopupMenuExt\FMX.PopupMenuExt.Constants.pas',
  FMX.PopupMenuExt.Thread in '..\..\DevelopmentsCollection\FMX.PopupMenuExt\FMX.PopupMenuExt.Thread.pas',
  PopupMenuExt.Item in '..\..\DevelopmentsCollection\FMX.PopupMenuExt\PopupMenuExt.Item.pas',
  AddLogUnit in '..\..\DevelopmentsCollection\AddLogUnit.pas',
  BinFileTypes in '..\..\DevelopmentsCollection\Types\BinFileTypes.pas',
  StreamHandler in '..\..\DevelopmentsCollection\Stream\StreamHandler.pas';

begin
  Application.Initialize;
  Application.CreateForm(TMainForm, MainForm);
  Application.Run;
end.
