program MemoryCells;

{$R *.res}

{$R *.dres}

uses
  System.StartUpCopy,
  FMX.Forms,
  MemoryCellsUnit in 'MemoryCellsUnit.pas' {MainForm},
  ToolsUnit in '..\..\DevelopmentsCollection\ToolsUnit.pas',
  DBToolsUnit in '..\..\DevelopmentsCollection\DBToolsUnit.pas',
  ParamsClassUnit in '..\..\DevelopmentsCollection\ParamsClassUnit.pas',
  BaseThreadUnit in 'Threads\BaseThreadUnit.pas',
  CloseFormThreadUnit in 'Threads\CloseFormThreadUnit.pas',
  DeleteFolderThreadUnit in 'Threads\DeleteFolderThreadUnit.pas',
  InsertCellThreadUnit in 'Threads\InsertCellThreadUnit.pas',
  InsertFolderThreadUnit in 'Threads\InsertFolderThreadUnit.pas',
  LoadCellThreadUnit in 'Threads\LoadCellThreadUnit.pas',
  UpdateCellThreadUnit in 'Threads\UpdateCellThreadUnit.pas',
  UpdateFolderThreadUnit in 'Threads\UpdateFolderThreadUnit.pas',
  BorderFrameUnit in '..\..\DevelopmentsCollection\BorderFrame\BorderFrameUnit.pas' {BorderFrame: TFrame},
  BaseCellFrameUnit in 'Frames\BaseCellFrameUnit.pas' {BaseCellFrame: TFrame},
  CurrentFolderFrameUnit in 'Frames\CurrentFolderFrameUnit.pas' {CurrentFolderFrame: TFrame},
  EditFolderNameFrameUnit in 'Frames\EditFolderNameFrameUnit.pas' {EditFolderNameFrame: TFrame},
  CellUnitFrameUnit in 'Frames\CellUnitFrameUnit.pas' {CellUnitFrame: TFrame},
  FolderUnitFrameUnit in 'Frames\FolderUnitFrameUnit.pas' {FolderUnitFrame: TFrame},
  CellMemoFrameUnit in 'Frames\CellMemoFrameUnit.pas' {CellMemoFrame: TFrame},
  DeleteCellThreadUnit in 'Threads\DeleteCellThreadUnit.pas',
  SearchThreadUnit in 'Threads\SearchThreadUnit.pas',
  LoadCatalogThreadUnit in 'Threads\LoadCatalogThreadUnit.pas',
  LoadCellsByIdListThreadUnit in 'Threads\LoadCellsByIdListThreadUnit.pas',
  SearchTextFrameUnit in 'Frames\SearchTextFrameUnit.pas' {SearchTextFrame: TFrame},
  BackupThreadUnit in 'Threads\BackupThreadUnit.pas',
  BackupStarterThreadUnit in 'BackupStarterThreadUnit.pas',
  UpdateCellAttributesThreadUnit in 'Threads\UpdateCellAttributesThreadUnit.pas',
  DestinationFolderNavigatorFrameUnit in 'Frames\DestinationFolderNavigatorFrameUnit.pas' {DestinationFolderNavigatorFrame: TFrame},
  LoadDestinationCatalogThreadUnit in 'Threads\LoadDestinationCatalogThreadUnit.pas',
  ThreadRegistryUnit in '..\..\DevelopmentsCollection\ThreadRegistryUnit.pas',
  MoveCellsThreadUnit in 'Threads\MoveCellsThreadUnit.pas',
  KeyCatcherThreadUnit in 'Threads\KeyCatcherThreadUnit.pas',
  KeyHandlerUnit in 'KeyHandlerUnit.pas',
  MemoryFileUnit in '..\..\DevelopmentsCollection\MemoryFileUnit.pas',
  TransportContainerUnit in '..\..\DevelopmentsCollection\UTCS\TransportContainerUnit.pas',
  UTCSTypesUnit in '..\..\DevelopmentsCollection\UTCS\UTCSTypesUnit.pas',
  UTClientManagerUnit in 'UTClientManagerUnit.pas',
  LockedListExtUnit in '..\..\DevelopmentsCollection\LockedListExtUnit.pas',
  UTClientUnit in '..\..\DevelopmentsCollection\UTCS\UTClientUnit.pas',
  UTClientRequestUnit in '..\MemoryCellsCommon\UTClientRequestUnit.pas',
  PingTimeoutThreadUnit in '..\..\DevelopmentsCollection\UTCS\PingTimeoutThreadUnit.pas',
  DBAccessUnit in '..\MemoryCellsCommon\DBAccessUnit.pas',
  CellUnit in '..\MemoryCellsCommon\CellUnit.pas',
  SQLTemplatesUnit in '..\..\DevelopmentsCollection\SQLTemplatesUnit.pas',
  ParamsExtUnit in '..\MemoryCellsCommon\ParamsExtUnit.pas',
  ExceptionContainerUnit in '..\MemoryCellsCommon\ExceptionContainerUnit.pas',
  ServerRepliesParserUnit in 'ServerRepliesParserUnit.pas',
  UTServerReplyUnit in '..\MemoryCellsCommon\UTServerReplyUnit.pas',
  FMX.MemoTextHighlighterUnit in '..\..\DevelopmentsCollection\FMX.MemoTextHighlighterUnit.pas',
  AddLogUnit in '..\..\DevelopmentsCollection\AddLogUnit.pas',
  FMX.ShowNoteFormUnit in '..\..\DevelopmentsCollection\FMX.ShowNoteFormUnit\FMX.ShowNoteFormUnit.pas' {NoteForm},
  FMX.ShowStatusUnit in 'FMX.ShowStatusUnit.pas',
  SupportUnit in '..\..\DevelopmentsCollection\SupportUnit.pas',
  FMX.TrayIcon.Win in '..\..\DevelopmentsCollection\FMX.TrayIcon.Win.pas',
  CustomThreadUnit in '..\..\DevelopmentsCollection\CustomThreadUnit.pas',
  FMX.Craft.PopupMenu.Structures in '..\..\DevelopmentsCollection\FMX.Craft.PopupMenu\FMX.Craft.PopupMenu.Structures.pas',
  FMX.Craft.PopupMenu.Thread.Win in '..\..\DevelopmentsCollection\FMX.Craft.PopupMenu\FMX.Craft.PopupMenu.Thread.Win.pas',
  FMX.Craft.PopupMenu.Win in '..\..\DevelopmentsCollection\FMX.Craft.PopupMenu\FMX.Craft.PopupMenu.Win.pas',
  CellReminderDateTimeFrameUnit in 'Frames\CellReminderDateTimeFrameUnit.pas' {CellReminderDateTimeFrame: TFrame},
  FMX.DateTimeControlsTuningUnit in '..\..\DevelopmentsCollection\FMX.DateTimeControlsTuningUnit.pas',
  LoadCellReminderThreadUnit in 'Threads\LoadCellReminderThreadUnit.pas',
  CellReminderThreadUnit in 'Threads\CellReminderThreadUnit.pas',
  FMX.OnClickReplacerUnit in '..\..\DevelopmentsCollection\FMX.OnClickReplacerUnit.pas',
  CellReminderFormUnit in 'Forms\CellReminderFormUnit.pas' {CellReminderForm},
  FMX.ThemeUnit in 'FMX.ThemeUnit.pas',
  UpdateCellReminderThreadUnit in 'Threads\UpdateCellReminderThreadUnit.pas',
  CommonUnit in 'CommonUnit.pas',
  BaseSettingUnit in 'Frames\Settings\BaseSettingUnit.pas' {BaseSettingFrame: TFrame},
  BackupSettingFrameUnit in 'Frames\Settings\BackupSettingFrameUnit.pas' {BackupSettingFrame: TFrame},
  LaunchSettingFrameUnit in 'Frames\Settings\LaunchSettingFrameUnit.pas' {LaunchSettingFrame: TFrame},
  SettingsFrameUnit in 'Frames\Settings\SettingsFrameUnit.pas' {SettingsFrame: TFrame},
  FileToolsUnit in '..\..\DevelopmentsCollection\FileToolsUnit.pas',
  FMX.ImageToolsUnit in '..\..\DevelopmentsCollection\FMX.ImageToolsUnit.pas';

begin
  Application.Initialize;
  Application.CreateForm(TMainForm, MainForm);
  Application.Run;
end.
